### ISSUE TITLE
gadget/network: Investigate why CI failed with 'fatal error: concurrent map writes'

### ISSUE THREAD

**Issue by mqasimsarfraz** [inspektor-gadget/inspektor-gadget#1304]
`TestTraceNetwork` failed in one of the [CI run](https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/4045684168/attempts/1#summary-10980106806) with following error. Given re-trigger fixed the issue it seem some a race condition but it needs to be investigated further:

```
fatal error: concurrent map writes

goroutine 14 [running]:
runtime.throw({0x1a85ba0?, 0x0?})
	/usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc000d4bb08 sp=0xc000d4bad8 pc=0x435d91
runtime.mapassign_fast64(0xc000002f54?, 0x17a6d40?, 0xf0000299)
	/usr/local/go/src/runtime/map_fast64.go:102 +0x2c5 fp=0xc000d4bb40 sp=0xc000d4bb08 pc=0x4137e5
github.com/inspektor-gadget/inspektor-gadget/pkg/gadgets/trace/network/tracer.(*Tracer).Attach(0xc00033d900, 0x2f54)
	/go/src/github.com/inspektor-gadget/inspektor-gadget/pkg/gadgets/trace/network/tracer/tracer.go:159 +0x648 fp=0xc000d4bd58 sp=0xc000d4bb40 pc=0x15094a8
github.com/inspektor-gadget/inspektor-gadget/pkg/container-collection/networktracer.ConnectToContainerCollection[...].func1()
	/go/src/github.com/inspektor-gadget/inspektor-gadget/pkg/container-collection/networktracer/connect.go:93 +0x1c8 fp=0xc000d4bf08 sp=0xc000d4bd58 pc=0x1550288
github.com/inspektor-gadget/inspektor-gadget/pkg/container-collection/networktracer.ConnectToContainerCollection[...].func3()
	/go/src/github.com/inspektor-gadget/inspektor-gadget/pkg/container-collection/networktracer/connect.go:119 +0x46 fp=0xc000d4bf20 sp=0xc000d4bf08 pc=0x154fda6
github.com/inspektor-gadget/inspektor-gadget/pkg/container-collection.(*ContainerCollection).Subscribe.func1({{0xc000e32fa8?, 0x0?}, 0x2a24ec0?, 0xc0017501e0?})
	/go/src/github.com/inspektor-gadget/inspektor-gadget/pkg/container-collection/container-collection.go:399 +0x6c fp=0xc000d4bf78 sp=0xc000d4bf20 pc=0x13c71ec
github.com/inspektor-gadget/inspektor-gadget/pkg/container-collection.(*GadgetPubSub).Publish.func1(0xc00000e780)
	/go/src/github.com/inspektor-gadget/inspektor-gadget/pkg/container-collection/pubsub.go:125 +0x62 fp=0xc000d4bfc8 sp=0xc000d4bf78 pc=0x13cb082
github.com/inspektor-gadget/inspektor-gadget/pkg/container-collection.(*GadgetPubSub).Publish.func2()
	/go/src/github.com/inspektor-gadget/inspektor-gadget/pkg/container-collection/pubsub.go:127 +0x2a fp=0xc000d4bfe0 sp=0xc000d4bfc8 pc=0x13cafea
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000d4bfe8 sp=0xc000d4bfe0 pc=0x465ca1
created by github.com/inspektor-gadget/inspektor-gadget/pkg/container-collection.(*GadgetPubSub).Publish
	/go/src/github.com/inspektor-gadget/inspektor-gadget/pkg/container-collection/pubsub.go:119 +0x196

goroutine 1 [runnable]:
encoding/binary.Read({0x1ce3d40, 0xc004242fc0}, {0x1d0f770, 0x2a5c340}, {0x19849a0?, 0xc000935040})
	/usr/local/go/src/encoding/binary/binary.go:162 +0x12d8
github.com/cilium/ebpf/btf.readTypes({0x1ce3d40, 0xc004242fc0}, {0x1d0f770, 0x2a5c340}, 0x494)
	/go/pkg/mod/github.com/inspektor-gadget/ebpf@v0.0.0-20230117151558-ea299d354cf6/btf/btf_types.go:309 +0x108
github.com/cilium/ebpf/btf.parseBTF({0x1ce7d60?, 0xc004259da0}, {0x1d0f770, 0x2a5c340}, 0xc1?)
	/go/pkg/mod/github.com/inspektor-gadget/ebpf@v0.0.0-20230117151558-ea299d354cf6/btf/btf.go:423 +0x3af
github.com/cilium/ebpf/btf.loadRawSpec({0x1ce7d60?, 0xc004259da0?}, {0x1d0f770?, 0x2a5c340?}, {0x0, 0x0, 0x0}, 0xc0001ba150?)
	/go/pkg/mod/github.com/inspektor-gadget/ebpf@v0.0.0-20230117151558-ea299d354cf6/btf/btf.go:218 +0x65
github.com/cilium/ebpf/btf.loadSpecFromELF(0xc00038e058)
	/go/pkg/mod/github.com/inspektor-gadget/ebpf@v0.0.0-20230117151558-ea299d354cf6/btf/btf.go:202 +0x26a
github.com/cilium/ebpf/btf.LoadSpecAndExtInfosFromReader({0x1ce3e00?, 0xc004259680?})
	/go/pkg/mod/github.com/inspektor-gadget/ebpf@v0.0.0-20230117151558-ea299d354cf6/btf/btf.go:117 +0x3a
github.com/cilium/ebpf.LoadCollectionSpecFromReader({0x1ce3e00, 0xc004259680})
	/go/pkg/mod/github.com/inspektor-gadget/ebpf@v0.0.0-20230117151558-ea299d354cf6/elf_reader.go:104 +0xa65
github.com/inspektor-gadget/inspektor-gadget/pkg/gadgets/trace/network/tracer.loadGraph()
	/go/src/github.com/inspektor-gadget/inspektor-gadget/pkg/gadgets/trace/network/tracer/graph_bpfel.go:28 +0x99
github.com/inspektor-gadget/inspektor-gadget/pkg/gadgets/trace/network/tracer.(*Tracer).Attach(0xc00033d900, 0x9ee)
	/go/src/github.com/inspektor-gadget/inspektor-gadget/pkg/gadgets/trace/network/tracer/tracer.go:121 +0x1f5
github.com/inspektor-gadget/inspektor-gadget/pkg/container-collection/networktracer.ConnectToContainerCollection[...].func1()
	/go/src/github.com/inspektor-gadget/inspektor-gadget/pkg/container-collection/networktracer/connect.go:93 +0x1c8
github.com/inspektor-gadget/inspektor-gadget/pkg/container-collection/networktracer.ConnectToContainerCollection[...](0xc00058fca0)
	/go/src/github.com/inspektor-gadget/inspektor-gadget/pkg/container-collection/networktracer/connect.go:127 +0x418
github.com/inspektor-gadget/inspektor-gadget/cmd/local-gadget/trace.newNetworkCmd.func1(0xc000308500, {0x1a6cec0, 0x3, 0x3})
	/go/src/github.com/inspektor-gadget/inspektor-gadget/cmd/local-gadget/trace/network.go:102 +0x4bc
github.com/spf13/cobra.(*Command).execute(0xc000308500, {0xc000302d80, 0x3, 0x3})
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001e5900)
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
	/go/src/github.com/inspektor-gadget/inspektor-gadget/cmd/local-gadget/main.go:49 +0x168

goroutine 8 [syscall]:
syscall.Syscall6(0x10f, 0xc000dc64b0, 0xa, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/asm_linux_amd64.s:43 +0x5
golang.org/x/sys/unix.ppoll(0x7fcae1756bd8?, 0xffffffffffffffff?, 0x0?, 0x50?)
	/go/pkg/mod/golang.org/x/sys@v0.2.0/unix/zsyscall_linux.go:124 +0x58
golang.org/x/sys/unix.Ppoll({0xc000dc64b0?, 0xc000336930?, 0xc001732570?}, 0x17c1180?, 0xc0017324f8?)
	/go/pkg/mod/golang.org/x/sys@v0.2.0/unix/syscall_linux.go:149 +0x45
golang.org/x/sys/unix.Poll({0xc000dc64b0?, 0xc00005fe97?, 0xc0000c8840?}, 0x0?)
	/go/pkg/mod/golang.org/x/sys@v0.2.0/unix/syscall_linux.go:158 +0x99
github.com/inspektor-gadget/inspektor-gadget/pkg/runcfanotify.(*RuncNotifier).watchContainersTermination(0xc000138320)
	/go/src/github.com/inspektor-gadget/inspektor-gadget/pkg/runcfanotify/runcfanotify.go:306 +0x231
created by github.com/inspektor-gadget/inspektor-gadget/pkg/runcfanotify.NewRuncNotifier
	/go/src/github.com/inspektor-gadget/inspektor-gadget/pkg/runcfanotify/runcfanotify.go:203 +0x2ac

goroutine 6 [IO wait]:
internal/poll.runtime_pollWait(0x7fcae2154f40, 0x72)
	/usr/local/go/src/runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc0003efc00?, 0xc000315000?, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0xc0003efc00, {0xc000315000, 0x1000, 0x1000})
	/usr/local/go/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc0003efc00, {0xc000315000?, 0x407ce9?, 0x4?})
	/usr/local/go/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc000191a20, {0xc000315000?, 0x0?, 0x0?})
	/usr/local/go/src/net/net.go:183 +0x45
net/http.(*persistConn).Read(0xc000423320, {0xc000315000?, 0xc0000c8a20?, 0xc00006ad30?})
	/usr/local/go/src/net/http/transport.go:1929 +0x4e
bufio.(*Reader).fill(0xc0002f52c0)
	/usr/local/go/src/bufio/bufio.go:106 +0x103
bufio.(*Reader).Peek(0xc0002f52c0, 0x1)
	/usr/local/go/src/bufio/bufio.go:144 +0x5d
net/http.(*persistConn).readLoop(0xc000423320)
	/usr/local/go/src/net/http/transport.go:2093 +0x1ac
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1750 +0x173e

goroutine 7 [select]:
net/http.(*persistConn).writeLoop(0xc000423320)
	/usr/local/go/src/net/http/transport.go:2392 +0xf5
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1751 +0x1791

goroutine 9 [IO wait]:
internal/poll.runtime_pollWait(0x7fcae2154e50, 0x72)
	/usr/local/go/src/runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc00003c1e0?, 0xc0000df000?, 0x1)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0xc00003c1e0, {0xc0000df000, 0x1000, 0x1000})
	/usr/local/go/src/internal/poll/fd_unix.go:167 +0x25a
os.(*File).read(...)
	/usr/local/go/src/os/file_posix.go:31
os.(*File).Read(0xc000191720, {0xc0000df000?, 0x0?, 0x7fcb0a5e05b8?})
	/usr/local/go/src/os/file.go:119 +0x5e
bufio.(*Reader).Read(0xc00003c240, {0xc000e330c8, 0x18, 0x44c872?})
	/usr/local/go/src/bufio/bufio.go:236 +0x1b4
io.ReadAtLeast({0x1ce3d40, 0xc00003c240}, {0xc000e330c8, 0x18, 0x18}, 0x18)
	/usr/local/go/src/io/io.go:331 +0x9a
io.ReadFull(...)
	/usr/local/go/src/io/io.go:350
encoding/binary.Read({0x1ce3d40, 0xc00003c240}, {0x1d0f770, 0x2a5c340}, {0x1872de0?, 0xc000e330b0})
	/usr/local/go/src/encoding/binary/binary.go:256 +0xc3e
github.com/s3rj1k/go-fanotify/fanotify.(*NotifyFD).GetEvent(0xc000306320, {0x0, 0x0, 0x0?})
	/go/pkg/mod/github.com/s3rj1k/go-fanotify/fanotify@v0.0.0-20210917134616-9c00a300bb7a/fanotify.go:194 +0x65
github.com/inspektor-gadget/inspektor-gadget/pkg/runcfanotify.(*RuncNotifier).watchRuncIterate(0xc000138320)
	/go/src/github.com/inspektor-gadget/inspektor-gadget/pkg/runcfanotify/runcfanotify.go:573 +0x5f
github.com/inspektor-gadget/inspektor-gadget/pkg/runcfanotify.(*RuncNotifier).watchRunc(0xc000138320)
	/go/src/github.com/inspektor-gadget/inspektor-gadget/pkg/runcfanotify/runcfanotify.go:554 +0x65
created by github.com/inspektor-gadget/inspektor-gadget/pkg/runcfanotify.NewRuncNotifier
	/go/src/github.com/inspektor-gadget/inspektor-gadget/pkg/runcfanotify/runcfanotify.go:207 +0x32a

goroutine 35 [semacquire]:
sync.runtime_Semacquire(0xc001727c38?)
	/usr/local/go/src/runtime/sema.go:56 +0x25
sync.(*WaitGroup).Wait(0xc00173fb90?)
	/usr/local/go/src/sync/waitgroup.go:136 +0x52
github.com/inspektor-gadget/inspektor-gadget/pkg/container-collection.(*GadgetPubSub).Publish(0xc0003065c0, 0x0, 0xc0017501e0)
	/go/src/github.com/inspektor-gadget/inspektor-gadget/pkg/container-collection/pubsub.go:130 +0x29d
github.com/inspektor-gadget/inspektor-gadget/pkg/container-collection.(*ContainerCollection).AddContainer(0xc0002e04d0, 0xc0017501e0)
	/go/src/github.com/inspektor-gadget/inspektor-gadget/pkg/container-collection/container-collection.go:176 +0xca
github.com/inspektor-gadget/inspektor-gadget/pkg/container-collection.WithRuncFanotify.func1.1({0x0, {0xc0000ffc17, 0x40}, 0x2f54, 0xc00170e000, {0xc0000ffbe4, 0x73}})
	/go/src/github.com/inspektor-gadget/inspektor-gadget/pkg/container-collection/options.go:516 +0xc7
github.com/inspektor-gadget/inspektor-gadget/pkg/runcfanotify.(*RuncNotifier).watchPidFileIterate(0xc000138320, 0xc000306000, {0xc0000ffbe4, 0x73}, {0xc0000ffc63, 0x7c}, {0xc0000ffc63, 0x73})
	/go/src/github.com/inspektor-gadget/inspektor-gadget/pkg/runcfanotify/runcfanotify.go:471 +0x65d
github.com/inspektor-gadget/inspektor-gadget/pkg/runcfanotify.(*RuncNotifier).monitorRuncInstance.func1()
	/go/src/github.com/inspektor-gadget/inspektor-gadget/pkg/runcfanotify/runcfanotify.go:533 +0x125
created by github.com/inspektor-gadget/inspektor-gadget/pkg/runcfanotify.(*RuncNotifier).monitorRuncInstance
	/go/src/github.com/inspektor-gadget/inspektor-gadget/pkg/runcfanotify/runcfanotify.go:529 +0x3ab
```

**Comment by mqasimsarfraz** [comment]
I am not able to reproduce it locally and nor this is happening in CI anymore. Reopen it in case we see this issue again!
