### ISSUE TITLE
ig "panic: getting host net ns inode" when /host not available

### ISSUE THREAD

**Issue by alban** [inspektor-gadget/inspektor-gadget#1858]
## Description

Running `ig` with `kubectl debug node` with the netadmin profile does not prepare the /host mount. Instead of returning an error, it panics.

## Impact

User is confused about what to do to solve the misconfiguration.

## Environment and steps to reproduce

```
$ kubectl debug --profile=netadmin node/controlplane -ti --image=ghcr.io/inspektor-gadget/ig -- ig trace exec --host --auto-mount-filesystems
Creating debugging pod node-debugger-controlplane-2v4xm with container debugger on node controlplane.
panic: getting host net ns inode: stat /host/proc/1/ns/net: no such file or directory

goroutine 1 [running]:
github.com/inspektor-gadget/inspektor-gadget/pkg/container-collection.WithLinuxNamespaceEnrichment()
        /go/src/github.com/inspektor-gadget/inspektor-gadget/pkg/container-collection/options.go:668 +0xaa
github.com/inspektor-gadget/inspektor-gadget/pkg/ig-manager.NewManager({0xc00058b1e0?, 0x4, 0x4})
        /go/src/github.com/inspektor-gadget/inspektor-gadget/pkg/ig-manager/ig-manager.go:98 +0x1d0
github.com/inspektor-gadget/inspektor-gadget/pkg/operators/localmanager.(*LocalManager).Init(0xc00047a5c0, 0xc000315788)
        /go/src/github.com/inspektor-gadget/inspektor-gadget/pkg/operators/localmanager/localmanager.go:194 +0x1a7
github.com/inspektor-gadget/inspektor-gadget/pkg/operators.(*operatorWrapper).Init.func1()
        /go/src/github.com/inspektor-gadget/inspektor-gadget/pkg/operators/operators.go:130 +0x37
sync.(*Once).doSlow(0xe9efc5?, 0xc0005df600?)
        /usr/local/go/src/sync/once.go:74 +0xc2
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:65
github.com/inspektor-gadget/inspektor-gadget/pkg/operators.(*operatorWrapper).Init(0x21a7060?, 0xc000120c90?)
        /go/src/github.com/inspektor-gadget/inspektor-gadget/pkg/operators/operators.go:129 +0x5d
github.com/inspektor-gadget/inspektor-gadget/pkg/operators.Operators.Init({0xc00048a000?, 0x1, 0x2778a38?}, 0x6?)
        /go/src/github.com/inspektor-gadget/inspektor-gadget/pkg/operators/operators.go:188 +0xaf
github.com/inspektor-gadget/inspektor-gadget/cmd/common.buildCommandFromGadget.func2(0xc0005dfdc8?, {0xc00058b000?, 0x7fff9f6e7e0a?, 0x2?})
        /go/src/github.com/inspektor-gadget/inspektor-gadget/cmd/common/registry.go:269 +0x4b5
github.com/spf13/cobra.(*Command).execute(0xc00042ac00, {0xc00058b000, 0x2, 0x2})
        /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc000354300)
        /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
        /go/src/github.com/inspektor-gadget/inspektor-gadget/cmd/ig/main.go:64 +0x1a5
```

## Expected behavior

The `pkg/utils/host` package detects the issue early and returns a proper error instead of panic().

**Comment by Iiqbal2000** [comment]
Hi @alban, can I take this issue?

**Comment by alban** [comment]
@Iiqbal2000 yes, thanks!

**Comment by Iiqbal2000** [comment]
Hi, @alban. I noticed the use of panic call in this segment:
https://github.com/inspektor-gadget/inspektor-gadget/blob/4cd764413dcf43f437f80f2f0f4fc7d9a75812e9/pkg/container-collection/options.go#L671

What do you think about encapsulating the `netnsHost, err := containerutils.GetNetNs(1)` code into the return function in the code block 
https://github.com/inspektor-gadget/inspektor-gadget/blob/4cd764413dcf43f437f80f2f0f4fc7d9a75812e9/pkg/container-collection/options.go#L674

So it will be like this:

```go
return func(cc *ContainerCollection) error {
	netnsHost, err := containerutils.GetNetNs(1)
	if err != nil {
		return fmt.Errorf("getting host net ns inode: %s", err)
	}
	// Rest of the code here
}

```

**Comment by alban** [comment]
@Iiqbal2000 I think that's a good solution.

**Comment by Iiqbal2000** [comment]
I am debugging it. Can you point me to the function that prints the column? @alban

**Comment by Iiqbal2000** [comment]
I got the function:

https://github.com/inspektor-gadget/inspektor-gadget/blob/d86b9b8e7800884c7781bdf1dea630245ea4a023/cmd/common/registry.go#L570C17-L570C17

The problem is that the function cannot determine whether the `ig` execution resulted in an error, so it always prints the column
