### ISSUE TITLE
`ig` + `cri-o` panic on enriching some `imageRef` fields 

### ISSUE THREAD

**Issue by burak-ok** [inspektor-gadget/inspektor-gadget#2413]
## `ig` + `cri-o` panic on enriching some `imageRef` fields 

On my local cri-o minikube I get the following error:
```
root@minikube-cri-o:~# ig list-containers --watch -o json
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/inspektor-gadget/inspektor-gadget/pkg/container-utils/cri.CRIContainerToContainerData({0x27d9493, 0x5}, {0x2b58230, 0xc0002ce850})
	/go/src/github.com/inspektor-gadget/inspektor-gadget/pkg/container-utils/cri/cri.go:306 +0x845
github.com/inspektor-gadget/inspektor-gadget/pkg/container-utils/cri.(*CRIClient).GetContainers(0xc00005d6c0)
	/go/src/github.com/inspektor-gadget/inspektor-gadget/pkg/container-utils/cri/cri.go:94 +0x8f
github.com/inspektor-gadget/inspektor-gadget/pkg/ig-manager.NewManager.WithMultipleContainerRuntimesEnrichment.WithContainerRuntimeEnrichment.func10(0xc000549600)
	/go/src/github.com/inspektor-gadget/inspektor-gadget/pkg/container-collection/options.go:169 +0x379
github.com/inspektor-gadget/inspektor-gadget/pkg/ig-manager.NewManager.WithMultipleContainerRuntimesEnrichment.func6(0xc000549600?)
	/go/src/github.com/inspektor-gadget/inspektor-gadget/pkg/container-collection/options.go:116 +0x56
github.com/inspektor-gadget/inspektor-gadget/pkg/container-collection.(*ContainerCollection).Initialize(0xc000549600, {0xc00058d4c0, 0x8, 0x0?})
	/go/src/github.com/inspektor-gadget/inspektor-gadget/pkg/container-collection/container-collection.go:103 +0x9b
github.com/inspektor-gadget/inspektor-gadget/pkg/ig-manager.NewManager({0xc00056e380, 0x4, 0x0?})
	/go/src/github.com/inspektor-gadget/inspektor-gadget/pkg/ig-manager/ig-manager.go:110 +0x565
github.com/inspektor-gadget/inspektor-gadget/cmd/ig/containers.NewListContainersCmd.func1(0xc00081ec00, {0x27d86ff, 0x4, 0x27d8703})
	/go/src/github.com/inspektor-gadget/inspektor-gadget/cmd/ig/containers/containers.go:52 +0xaf
github.com/spf13/cobra.(*Command).execute(0xc000004f00, {0xc000568cc0, 0x3, 0x3})
	/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0xabc
github.com/spf13/cobra.(*Command).ExecuteC(0xc000004600)
	/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
main.main()
	/go/src/github.com/inspektor-gadget/inspektor-gadget/cmd/ig/main.go:82 +0x30f
```

The problem seems to be the line `ContainerImageDigest: strings.Split(imageRef, "@")[1],` with the following `container`
```
ContainerName:  kube-controller-manager
ContainerImageName:  c6c20157a42337ecb7675be59e1dc34bc5a91288c7eeac1e30ec97767a9055eb
imageRef:  c6c20157a42337ecb7675be59e1dc34bc5a91288c7eeac1e30ec97767a9055eb
```

Additional info:
```
$ crane manifest k8s.gcr.io/kube-controller-manager:v1.24.6 | jq
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
  "manifests": [
    {
      "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
      "size": 949,
      "digest": "sha256:8200818d562ccdb25e5ca94f160fa64a569ca45578d8483b68ada9433405c9a5",
      "platform": {
        "architecture": "amd64",
        "os": "linux"
      }
    },
    ....
  ]
}
$ crane manifest k8s.gcr.io/kube-controller-manager@sha256:8200818d562ccdb25e5ca94f160fa64a569ca45578d8483b68ada9433405c9a5 | jq
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
  "config": {
    "mediaType": "application/vnd.docker.container.image.v1+json",
    "size": 1613,
    "digest": "sha256:c6c20157a42337ecb7675be59e1dc34bc5a91288c7eeac1e30ec97767a9055eb"
  },
  "layers": [
    ...
  ]
}
```

**Comment by alban** [comment]
PR#2398 includes a patch with the fix.
