### ISSUE TITLE
gadgetctl/kubectl-gadget: Crash when running `attach` right after `run`  

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#3678]
Consider the following manifest:

```yaml
# manifest.yaml
apiVersion: 1
kind: instance-spec
image: trace_exec
name: mygadgetinstance
tags:
  - foo
  - bar
paramValues:
```

```bash
$ sudo gadgetctl run -f manifest.yaml --detach && sudo gadgetctl attach mygadgetinstance
INFO[0000] installed as "729e15bb1655c84211a742c8ff7479a7"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa0 pc=0x307ccc8]

goroutine 1 [running]:
github.com/inspektor-gadget/inspektor-gadget/pkg/gadget-context.(*GadgetContext).LoadGadgetInfo(0xc00052c820, 0x0, 0xc000130f00, 0x0)
        /home/mauriciov/kinvolk/ebpf/inspektor-gadget/pkg/gadget-context/gadget-context.go:320 +0xc8
github.com/inspektor-gadget/inspektor-gadget/pkg/runtime/grpc.(*Runtime).GetGadgetInfo(0xc0008b4870, {0x46fe7e0, 0xc00052c820}, 0xd?, 0xc000130f00)
        /home/mauriciov/kinvolk/ebpf/inspektor-gadget/pkg/runtime/grpc/oci.go:62 +0x32c
github.com/inspektor-gadget/inspektor-gadget/cmd/common.NewRunCommand.func1(0xc000754908, {0xc0003104c0, 0x1, 0x1})
        /home/mauriciov/kinvolk/ebpf/inspektor-gadget/cmd/common/oci.go:223 +0xc65
github.com/spf13/cobra.(*Command).execute(0xc000754908, {0xc0003104c0, 0x1, 0x1})
        /home/mauriciov/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:970 +0xa44
github.com/spf13/cobra.(*Command).ExecuteC(0xc0004be908)
        /home/mauriciov/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        /home/mauriciov/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
main.main()
        /home/mauriciov/kinvolk/ebpf/inspektor-gadget/cmd/gadgetctl/main.go:108 +0x905
````

Adding a sleep between the commands fixes it:

```bash
$ sudo gadgetctl run -f manifest.yaml --detach && sleep 2 && sudo gadgetctl attach mygadgetinstance
INFO[0000] installed as "77922556b8944cff8b2ace4ed3075e62"
RUNTIME.CONTAINERNAME                                    COMM                    PID        TID ARGS                               ERRO
```

**Comment by KapilSareen** [comment]
Hi @mauriciovasquezbernal, I’d like to work on this. Could you please provide more details on how you’d like it to function?

**Comment by KapilSareen** [comment]
Also I keep getting this error on trying to reproduce:

```bash
$ sudo gadgetctl run -f manifest.yaml --detach && sudo gadgetctl attach mygadgetinstance
Error: running gadget from manifest file: creating gadget instance: connecting to target "local": dialing "unix:///var/run/ig/ig.socket" ("local"): dialing "unix:///var/run/ig/ig.socket" ("local"): context deadline exceeded: connection error: desc = "transport: Error while dialing: dial unix /var/run/ig/ig.socket: connect: no such file or directory"
```
Is there a known fix?
